In [1]:
import pandas as pd
file_path = 'IHME_DAH_DATABASE_1990_2020_Y2021M09D22.CSV'
chunksize = 100000 
df_csv = pd.concat(pd.read_csv(file_path, chunksize=chunksize, encoding="utf-8", low_memory=False))

In [2]:
df_csv.head(10)

,year,source,channel,recipient_isocode,recipient_country,gbd_location_id,wb_regioncode,wb_location_id,gbd_region,gbd_region_id,...,other_dah_20,rmh_dah_20,nch_dah_20,ncd_dah_20,hiv_dah_20,mal_dah_20,tb_dah_20,swap_hss_total_dah_20,oid_dah_20,unalloc_dah_20
0,1990,Australia,BIL_AUS,AGO,Angola,168,SSA,242,"Sub-Saharan Africa, Central",167.0,...,0,5,0,0,7,3,0,0,0,-
1,1990,Australia,BIL_AUS,BDI,Burundi,175,SSA,242,"Sub-Saharan Africa, Eastern",174.0,...,0,6,0,0,5,1,0,0,0,0
2,1990,Australia,BIL_AUS,BEN,Benin,200,SSA,242,"Sub-Saharan Africa, Western",199.0,...,0,6,0,0,5,2,0,0,0,0
3,1990,Australia,BIL_AUS,BFA,Burkina Faso,201,SSA,242,"Sub-Saharan Africa, Western",199.0,...,0,5,0,0,7,2,0,0,0,0
4,1990,Australia,BIL_AUS,BWA,Botswana,193,SSA,242,"Sub-Saharan Africa, Southern",192.0,...,0,1,0,0,23,-,0,0,0,-
5,1990,Australia,BIL_AUS,CAF,Central African Republic,169,SSA,242,"Sub-Saharan Africa, Central",167.0,...,0,1,0,0,2,-,0,0,0,-
6,1990,Australia,BIL_AUS,CHN,China,6,EAP,239,"Asia, East",5.0,...,38,7,0,0,367,5,0,130,0,0
7,1990,Australia,BIL_AUS,CIV,Cote d'Ivoire,205,SSA,242,"Sub-Saharan Africa, Western",199.0,...,0,5,0,0,18,1,0,0,0,0
8,1990,Australia,BIL_AUS,CMR,Cameroon,202,SSA,242,"Sub-Saharan Africa, Western",199.0,...,0,2,0,0,8,1,0,0,0,-
9,1990,Australia,BIL_AUS,COD,Democratic Republic of the Congo,171,SSA,242,"Sub-Saharan Africa, Central",167.0,...,0,14,0,0,18,6,0,0,0,0

In [4]:
cols_to_convert = df_csv.columns[14:]
df_csv[cols_to_convert] = df_csv[cols_to_convert].apply(pd.to_numeric, errors='coerce')

In [5]:
import numpy as np

In [6]:
mean_val = np.mean(df_csv["dah_20"])

In [7]:
print(mean_val)

2519.3625352650447

In [12]:
df_csv.dropna(subset=["dah_20"], inplace=True)
median_val = np.median(df_csv["dah_20"])
print(median_val)

44.0

In [13]:
std_dev = np.std(df_csv["dah_20"])
print(std_dev)

36693.2562089067

In [14]:
variance = np.var(df_csv["dah_20"])
print(variance)

1346395051.2124703

In [17]:
df_csv.dropna(subset=["other_dah_20"], inplace=True)
data_1 = df_csv["other_dah_20"]
data_2 = df_csv["dah_20"]
correlation = np.corrcoef(data_1, data_2)[0, 1]
print(correlation)

0.753662974820274

In [18]:
covariance = np.cov(data_1, data_2)[0, 1]
print(covariance)

213078437.0006457